name: Pull Request Validation

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install platform-specific dependencies
        run: |
          # Install oxlint platform dependency for Linux (temporary, not saved to package.json)
          npm install @oxlint/linux-x64-gnu --no-save || echo "Failed to install oxlint platform dependency, continuing..."

      - name: Check formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install platform-specific dependencies
        run: |
          # Install Rollup platform dependency for Linux (temporary, not saved to package.json)
          npm install @rollup/rollup-linux-x64-gnu --no-save || echo "Failed to install Rollup platform dependency, continuing..."

      - name: Build project (CI - skip visualizer)
        run: npm run build:ci

      - name: Run tests
        run: npm run test:run
        env:
          INCLUDE_NOISY_TESTS: true
          LOG_LEVEL: ERROR
